In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from time import time

data_base_dir = '../../datasets/Movielens/'
data_dir2 = data_base_dir + 'Movielens Latest/ml-latest/'
data_dir = data_base_dir + 'ml-20m/'

genome_scores = data_dir2 + 'genome-scores.csv'
genome_tags = data_dir + 'genome-tags.csv'
movies = data_dir + 'movies.csv'
ratings = data_dir + 'ratings.csv'
tags = data_dir + 'tags.csv'
genres = data_dir + 'u.genre'

user_unstemmed_genome_vector = data_dir + 'user_unstemmed_genome_terms_df_gzip'
user_stemmed_genome_vector = data_dir + 'user_stemmed_genome_terms_df_gzip'

In [2]:
user_genome_vector_df = pd.read_pickle(user_unstemmed_genome_vector, compression='gzip')
user_genome_vector_df

tagId       1         2         3         4         5         6         7     \
1       0.052600  0.042993  0.127963  0.094743  0.156503  0.137389  0.085049   
2       0.062377  0.067836  0.105873  0.082725  0.123098  0.179541  0.106422   
3       0.056675  0.056186  0.086004  0.087451  0.150430  0.175574  0.102398   
4       0.101384  0.107277  0.055786  0.059589  0.098839  0.103884  0.068929   
5       0.058208  0.040087  0.118318  0.078848  0.155500  0.136015  0.085958   
6       0.098042  0.091917  0.093104  0.067958  0.092500  0.096229  0.064167   
7       0.048801  0.047246  0.097186  0.087468  0.158333  0.164096  0.089639   
8       0.074950  0.066996  0.085775  0.063636  0.096804  0.099386  0.060539   
9       0.070193  0.063621  0.034814  0.052950  0.079114  0.087600  0.066193   
10      0.062013  0.055770  0.096559  0.133184  0.243914  0.215053  0.158921   
11      0.052602  0.041444  0.076835  0.062757  0.095485  0.088929  0.046068   
12      0.080514  0.067951  0.099854  0.069382  0.108715  0.123549  0.066486   
13      0.067258  0.054327  0.089391  0.065315  0.110395  0.122702  0.064552   
14      0.043725  0.036930  0.125035  0.110495  0.187857  0.169806  0.086956   
15      0.071097  0.056582  0.104923  0.075133  0.142138  0.152296  0.078469   
16      0.037371  0.038325  0.077542  0.082883  0.127146  0.175692  0.071150   
17      0.143856  0.098558  0.113538  0.078423  0.108615  0.120673  0.083394   
18      0.032382  0.030223  0.075048  0.086091  0.137395  0.145911  0.092944   
19      0.060220  0.064335  0.074040  0.052355  0.081475  0.074795  0.055675   
20      0.043937  0.034500  0.049214  0.076161  0.148241  0.153920  0.066366   
21      0.044877  0.040408  0.101181  0.099474  0.186551  0.194245  0.112684   
22      0.064372  0.054455  0.057231  0.065299  0.120985  0.093182  0.053188   
23      0.049365  0.041370  0.092596  0.079498  0.126694  0.124341  0.055944   
24      0.057692  0.047653  0.071784  0.064378  0.100271  0.097184  0.052191   
25      0.044944  0.031262  0.083919  0.082773  0.159457  0.153981  0.094740   
26      0.066840  0.054176  0.087152  0.065496  0.111275  0.126730  0.062705   
27      0.067598  0.037833  0.104913  0.081203  0.110167  0.129051  0.073554   
28      0.054930  0.038703  0.102383  0.064992  0.126508  0.115633  0.062977   
29      0.048596  0.045973  0.090989  0.058394  0.104994  0.086843  0.054226   
30      0.045419  0.039782  0.073677  0.077815  0.151573  0.099427  0.075750   
...          ...       ...       ...       ...       ...       ...       ...   
138464  0.072834  0.067379  0.083378  0.071517  0.124896  0.103327  0.059960   
138465  0.041117  0.035234  0.114008  0.101133  0.147977  0.167266  0.070102   
138466  0.043906  0.031336  0.159258  0.079516  0.127906  0.147312  0.091922   
138467  0.044254  0.042391  0.098759  0.093635  0.158776  0.143664  0.075902   
138468  0.032716  0.024948  0.085224  0.103147  0.169845  0.149483  0.073147   
138469  0.040955  0.032273  0.132739  0.156966  0.242568  0.196511  0.065420   
138470  0.052134  0.049348  0.088091  0.076129  0.121187  0.119359  0.054629   
138471  0.066811  0.049944  0.094719  0.076329  0.120288  0.110537  0.053497   
138472  0.047011  0.037086  0.074134  0.080209  0.128425  0.114820  0.068765   
138473  0.030189  0.026325  0.075872  0.077511  0.123903  0.096325  0.057158   
138474  0.054749  0.048091  0.063862  0.059944  0.104929  0.096009  0.055425   
138475  0.024818  0.024484  0.140408  0.220389  0.308997  0.328073  0.139354   
138476  0.037798  0.034462  0.126115  0.075933  0.091875  0.078337  0.047663   
138477  0.054527  0.039778  0.083879  0.079861  0.132815  0.122686  0.079902   
138478  0.035970  0.031707  0.107250  0.083573  0.118274  0.124335  0.074701   
138479  0.048864  0.041014  0.107757  0.086621  0.121779  0.127364  0.047436   
138480  0.089417  0.094595  0.060667  0.061762  0.082071  0.086786  0.058405   
138481  0.060483  0.034208  0.072033  0.087400  0.157975  0.193583  0.081275   


In [3]:
from scipy.spatial.distance import cosine
user1 = 1
user2 = 2
genresA = user_genome_vector_df.loc[user1, :]
genresB = user_genome_vector_df.loc[user2, :]
cosine(genresA, genresB)

0.016823214475762738

In [4]:
genome_scores_df = pd.read_csv(genome_scores)
genome_scores_df = genome_scores_df.pivot(index='movieId', columns='tagId', values='relevance')
genome_scores_df

tagId       1        2        3        4        5        6        7     \
movieId                                                                  
1        0.02900  0.02375  0.05425  0.06875  0.16000  0.19525  0.07600   
2        0.03625  0.03625  0.08275  0.08175  0.10200  0.06900  0.05775   
3        0.04150  0.04950  0.03000  0.09525  0.04525  0.05925  0.04000   
4        0.03350  0.03675  0.04275  0.02625  0.05250  0.03025  0.02425   
5        0.04050  0.05175  0.03600  0.04625  0.05500  0.08000  0.02150   
6        0.02925  0.02575  0.02700  0.03450  0.06825  0.04675  0.04675   
7        0.04775  0.05075  0.13400  0.08825  0.09550  0.19500  0.05400   
8        0.03125  0.03750  0.08050  0.03150  0.05100  0.01750  0.01475   
9        0.03225  0.03550  0.02150  0.01650  0.02350  0.01975  0.01450   
10       0.99950  1.00000  0.03050  0.05150  0.07850  0.08550  0.12125   
11       0.03500  0.03925  0.21675  0.07200  0.09500  0.08925  0.04575   
12       0.03575  0.03275  0.03625  0.03550  0.22550  0.02375  0.01700   
13       0.02400  0.02550  0.04550  0.03575  0.03250  0.03925  0.01375   
14       0.02375  0.02375  0.04500  0.12275  0.12375  0.11525  0.22525   
15       0.04325  0.05025  0.32325  0.02625  0.03975  0.03700  0.01675   
16       0.03250  0.02825  0.02250  0.08775  0.19575  0.09175  0.07575   
17       0.02750  0.02950  0.98050  0.14575  0.21050  0.11675  0.07450   
18       0.03175  0.03000  0.02900  0.05975  0.05300  0.02250  0.01825   
19       0.03675  0.03825  0.02575  0.03525  0.05775  0.07200  0.01975   
20       0.04325  0.04800  0.02000  0.03075  0.04550  0.03075  0.02425   
21       0.03000  0.03125  0.03500  0.11900  0.18025  0.11575  0.03450   
22       0.02875  0.03250  0.03200  0.03200  0.09850  0.04500  0.02825   
23       0.12900  0.13050  0.02400  0.02350  0.03700  0.01475  0.03200   
24       0.02775  0.02825  0.02575  0.02675  0.05650  0.06725  0.03450   
25       0.02325  0.02000  0.03425  0.03925  0.04875  0.06100  0.01775   
26       0.02950  0.03575  0.24225  0.13400  0.19575  0.03875  0.02175   
27       0.02675  0.02975  0.03100  0.04550  0.04900  0.09850  0.14775   
28       0.03150  0.03450  0.96175  0.14075  0.15000  0.04850  0.03700   
29       0.02350  0.02375  0.19775  0.20575  0.12150  0.08300  0.04700   
30       0.02750  0.03200  0.18650  0.22350  0.86675  0.10375  0.12850   
...          ...      ...      ...      ...      ...      ...      ...   
182913   0.07050  0.13750  0.07600  0.10425  0.15175  0.15475  0.13525   
183011   0.05950  0.04875  0.03050  0.04500  0.16500  0.04825  0.02400   
183197   0.05275  0.07775  0.09150  0.12400  0.26975  0.08375  0.21825   
183227   0.06725  0.08125  0.11450  0.08975  0.14150  0.06575  0.07650   
183421   0.15375  0.12550  0.03350  0.06975  0.10950  0.06825  0.13675   
183589   0.15450  0.07925  0.02700  0.03450  0.07500  0.03150  0.02875   
183611   0.05200  0.05125  0.05950  0.07750  0.16950  0.08225  0.03825   
183619   0.05550  0.02900  0.03125  0.04125  0.08250  0.21700  0.15300   
183635   0.06975  0.08650  0.06250  0.06700  0.08925  0.03975  0.03325   
183701   0.13050  0.14525  0.03500  0.03325  0.37575  0.05800  0.04500   
183833   0.05425  0.04550  0.17075  0.09275  0.08950  0.07275  0.06450   
183897   0.02725  0.02700  0.07650  0.17400  0.24825  0.20325  0.13850   
183909   0.04100  0.03225  0.09200  0.04975  0.07675  0.16950  0.09125   
184015   0.04050  0.03300  0.07275  0.06975  0.11625  0.04125  0.03725   
184017   0.05625  0.05075  0.06800  0.05875  0.33900  0.05075  0.03700   
184239   0.03325  0.02775  0.02975  0.08725  0.05475  0.02875  0.04200   
184253   0.12475  0.10525  0.07150  0.05300  0.11625  0.06000  0.04950   
184257   0.02400  0.01775  0.09000  0.12600  0.20575  0.21675  0.14150   
184471   0.06375  0.07425  0.03450  0.06725  0.11325  0.04600  0.01275   
184931   0.09875  0.08825  0.04925  0.06100  0.21600  0.06775  0.08175   
184987   0.01975  0.01650  0.13200  0.08500  0.09000  0.10000  0.04425   
1849

In [5]:
from sklearn.metrics import pairwise_distances_chunked
from sklearn.metrics import pairwise_distances
from time import time

start = time()

item_terms = genome_scores_df.values
# print(pairwise_distances(genresA[:20000], metric='cosine').shape)
item_item_distances = pairwise_distances(item_terms, metric='cosine')
print(item_item_distances)
print(item_item_distances.shape)
# print(next(chunked_D))
# print(next(chunked_D).shape)
# print(next(chunked_D).shape)
# print(next(chunked_D).shape)
finish = time() - start

print("Total Time: %f seconds" % finish)

[[0.         0.24003171 0.3115643  ... 0.3352507  0.26211715 0.23557765]
 [0.24003171 0.         0.32965451 ... 0.2917416  0.33365416 0.26622387]
 [0.3115643  0.32965451 0.         ... 0.2952598  0.2310223  0.25053072]
 ...
 [0.3352507  0.2917416  0.2952598  ... 0.         0.23583367 0.24933268]
 [0.26211715 0.33365416 0.2310223  ... 0.23583367 0.         0.1372013 ]
 [0.23557765 0.26622387 0.25053072 ... 0.24933268 0.1372013  0.        ]]
(13176, 13176)
Total Time: 2.685033 seconds


In [6]:
from sklearn.metrics import pairwise_distances

movies_vector = genome_scores_df.values

# take random N=20 users
N_Users = 20
all_user_ids = user_genome_vector_df.index.values

# randomly choose n_users, using the random seed
seed_number = 171450
np.random.seed(seed_number)

n_users = np.random.choice(all_user_ids, size=N_Users)

# find K similar items:
K = 20

# key - user_id, value - series with movie_id as index and relevance score to user profile as value, 
# where series name is as same as user_id
k_similar_items_dict = dict()

def top_K_similar_movies(user_id, K, all_movies_vector):
    user_vector = user_genome_vector_df.loc[user_id, :].values

    # convert from 1D to 2D array
    user_vector = np.array([user_vector])

    start = time()
    distances = pairwise_distances(all_movies_vector, user_vector, metric='cosine')
    finish = time() - start

    # 2D to 1D
    distances = distances.T[0]

    ser = pd.Series(distances, name=user_id)
    ser.index = genome_scores_df.index    

    # top K recommendations, with relevance scores to the user profile
    return ser.sort_values(ascending=False)[:K]

for user in n_users:
    series = top_K_similar_movies(user, K, movies_vector)
    k_similar_items_dict[user] = series

# Calculate Diversity and Serendipity Index
k_similar_items_dict

{133040: movieId
 4943      0.463297
 96691     0.458641
 80363     0.452435
 4982      0.449678
 117368    0.445784
 5806      0.442616
 5413      0.441802
 3687      0.437534
 82366     0.434690
 95932     0.433349
 55232     0.432440
 44243     0.431009
 6208      0.430585
 3216      0.428560
 110773    0.427357
 59935     0.426865
 43838     0.426664
 86835     0.426223
 5746      0.425237
 8004      0.424170
 Name: 133040, dtype: float64, 134178: movieId
 96691     0.542430
 80363     0.531353
 4943      0.528492
 110773    0.520248
 53464     0.520038
 92938     0.518867
 95932     0.518261
 94018     0.516570
 55232     0.510950
 8861      0.509820
 74075     0.507422
 117368    0.507325
 87430     0.507193
 39421     0.506431
 44243     0.504966
 43838     0.504841
 111630    0.504749
 43928     0.504606
 91660     0.504365
 59935     0.503896
 Name: 134178, dtype: float64, 128916: movieId
 96691     0.512012
 80363     0.507668
 95932     0.503566
 39421     0.498139
 4943    

# Ranking Algorithm

In [7]:
ratings_df = pd.read_csv(ratings, usecols=range(3), dtype={'userId':np.int64, 'movieId':np.int64, 'rating':np.float64}, low_memory=False)
genome_score_movies = genome_scores_df.index.unique()
ratings_df = ratings_df[ratings_df['movieId'].isin(genome_score_movies)]

In [8]:
K = 20
candidate_movie_id = 1



item_item_similarity_df = pd.DataFrame(item_item_distances, index=genome_scores_df.index, columns=genome_scores_df.index)
candidate_movies = [919, 924, 1967]
    
ranking_df = pd.DataFrame()

for candidate_movie_id in candidate_movies:
    similar_movies = item_item_similarity_df[candidate_movie_id].sort_values(ascending=False)[:K]

    similar_movies_df = pd.DataFrame(similar_movies)
    similar_movies_df['movieId'] = similar_movies_df.index
    similar_movies_df['candidate_movie_id'] = similar_movies.name
    similar_movies_df.columns = ['S_c', 'movieId', 'Candidate Movie Id']
    similar_movies_df.reset_index(drop=True, inplace=True)

    ranking_df = ranking_df.append(similar_movies_df, ignore_index=True)
    
ranking_df

S_c  movieId  Candidate Movie Id
0   0.629817    96691                 919
1   0.622633    80363                 919
2   0.621326   134246                 919
3   0.620348    50189                 919
4   0.618219     5891                 919
5   0.614325    39421                 919
6   0.607290     5717                 919
7   0.607167     8861                 919
8   0.606481   128592                 919
9   0.604573     6132                 919
10  0.604171     5160                 919
11  0.603042     5413                 919
12  0.602088    55232                 919
13  0.601420    90916                 919
14  0.599286    82366                 919
15  0.598467   104736                 919
16  0.597007    92938                 919
17  0.596884   116191                 919
18  0.596384     6000                 919
19  0.596342    53435                 919
20  0.664744   117368                 924
21  0.656645    54734                 924
22  0.645606    39421                 924
23  0.638894    44193                 924
24  0.637025    50189                 924
25  0.634817     8808                 924
26  0.634328     7169                 924
27  0.633632   110773                 924
28  0.631951    77665                 924
29  0.630887    47122                 924
30  0.629755     8869                 924
31  0.629642     6266                 924
32  0.629407    54278                 924
33  0.628614     8643                 924
34  0.628115     7450                 924
35  0.627276    43906                 924
36  0.626735    93326                 924
37  0.626615   134246                 924
38  0.626367     5620                 924
39  0.625870     5943                 924
40  0.628148     8140                1967
41  0.620583    95604                1967
42  0.609621   134246                1967
43  0.607522   104736                1967
44  0.600404   157338                1967
45  0.596366   161954                1967
46  0.595504    81641                1967
47  0.594674     1156                1967
48  0.589853   130474                1967
49  0.589229    48909                1967
50  0.587856     6073                1967
51  0.586604     4435                1967
52  0.582975     5806                1967
53  0.582721    33750                1967
54  0.580995    30721                1967
55  0.580897      787                1967
56  0.580283    26791                1967
57  0.579527    77810                1967
58  0.579470    51167                1967
59  0.578970   170645                1967

In [9]:
similar_movies

movieId
8140      0.628148
95604     0.620583
134246    0.609621
104736    0.607522
157338    0.600404
161954    0.596366
81641     0.595504
1156      0.594674
130474    0.589853
48909     0.589229
6073      0.587856
4435      0.586604
5806      0.582975
33750     0.582721
30721     0.580995
787       0.580897
26791     0.580283
77810     0.579527
51167     0.579470
170645    0.578970
Name: 1967, dtype: float64

In [10]:
# find similarity scores to the user profile for each movie in ranking_df
user_id = 1

movie_ids = ranking_df['movieId'].values
movie_ids

# extract genome scores for movie_ids
genome_scores_vector = genome_scores_df.loc[movie_ids, :].values

# extract user_term vector
user_vector = user_genome_vector_df.loc[user_id, :]

distances_with_user = pairwise_distances(genome_scores_vector, [user_vector], metric='cosine')
distances_with_user

ranking_df['S_u'] = distances_with_user
ranking_df['diversity'] = 1 - ranking_df['S_u']
ranking_df
# ranking_df['R_cu'] = 
users_ratings = ratings_df[ratings_df['userId'] == user_id].loc[:, ['movieId','rating']]
candidate_movie_ratings_df = users_ratings[users_ratings['movieId'].isin(candidate_movies)]
candidate_movie_ratings_df.set_index(candidate_movie_ratings_df['movieId'].values, drop=True, inplace=True)

movie_ratings_dict = candidate_movie_ratings_df['rating'].to_dict()
movie_ratings_dict

{919: 3.5, 924: 3.5, 1967: 4.0}

In [11]:
def assign_rating(x):
    x['R_cu'] = movie_ratings_dict[x['Candidate Movie Id']]
    
    return x

ranking_df['R_cu'] = None

ranking_df = ranking_df.apply(lambda x: assign_rating(x), axis=1)

# TODO add cluster rank as well
ranks = ranking_df.loc[:, ['S_c', 'S_u', 'diversity', 'R_cu']].rank(method='dense')
ranks

# ranking formula
# TODO add cluster ranking, also check how to calculate spearman ranking rather than below formula
ranking_df['composite_score'] = ranking_df['R_cu'] * ranking_df['diversity'] * ranking_df['S_u'] * ranking_df['S_c']
sorted_scores_df = ranking_df.sort_values('composite_score', ascending=False)

K = 20
sorted_scores_df.loc[:, ['movieId']][:K].values.reshape(1, -1)[0]
# from scipy.stats import spearmanr 
# spearmanr(ranks.values[0])[0]
# ranking_df.rank(method='dense')

array([  8140, 134246,  95604, 104736,   1156,   5806, 130474,  77810,
       117368,   6073,  26791, 157338,  81641,    787,  54734, 161954,
        33750,  39421, 170645,  50189])

In [12]:
ranking_df.sort_values('composite_score', ascending=False, inplace=True)
ranking_df
# ranks

S_c  movieId  Candidate Movie Id       S_u  diversity  R_cu  \
40  0.628148     8140                1967  0.438028   0.561972   4.0   
42  0.609621   134246                1967  0.437159   0.562841   4.0   
41  0.620583    95604                1967  0.393092   0.606908   4.0   
43  0.607522   104736                1967  0.416430   0.583570   4.0   
47  0.594674     1156                1967  0.442604   0.557396   4.0   
52  0.582975     5806                1967  0.463797   0.536203   4.0   
48  0.589853   130474                1967  0.429003   0.570997   4.0   
57  0.579527    77810                1967  0.468731   0.531269   4.0   
20  0.664744   117368                 924  0.452133   0.547867   3.5   
50  0.587856     6073                1967  0.429540   0.570460   4.0   
56  0.580283    26791                1967  0.457312   0.542688   4.0   
44  0.600404   157338                1967  0.394845   0.605155   4.0   
46  0.595504    81641                1967  0.401434   0.598566   4.0   
55  0.580897      787                1967  0.433163   0.566837   4.0   
21  0.656645    54734                 924  0.456535   0.543465   3.5   
45  0.596366   161954                1967  0.395021   0.604979   4.0   
53  0.582721    33750                1967  0.401588   0.598412   4.0   
22  0.645606    39421                 924  0.446732   0.553268   3.5   
59  0.578970   170645                1967  0.402790   0.597210   4.0   
24  0.637025    50189                 924  0.451356   0.548644   3.5   
23  0.638894    44193                 924  0.427634   0.572366   3.5   
26  0.634328     7169                 924  0.432740   0.567260   3.5   
58  0.579470    51167                1967  0.377678   0.622322   4.0   
30  0.629755     8869                 924  0.437582   0.562418   3.5   
25  0.634817     8808                 924  0.421689   0.578311   3.5   
29  0.630887    47122                 924  0.428962   0.571038   3.5   
27  0.633632   110773                 924  0.420495   0.579505   3.5   
0   0.629817    96691                 919  0.429743   0.570257   3.5   
37  0.626615   134246                 924  0.437159   0.562841   3.5   
3   0.620348    50189                 919  0.451356   0.548644   3.5   
33  0.628614     8643                 924  0.423587   0.576413   3.5   
2   0.621326   134246                 919  0.437159   0.562841   3.5   
31  0.629642     6266                 924  0.411370   0.588630   3.5   
39  0.625870     5943                 924  0.419574   0.580426   3.5   
51  0.586604     4435                1967  0.349483   0.650517   4.0   
34  0.628115     7450                 924  0.413707   0.586293   3.5   
28  0.631951    77665                 924  0.405500   0.594500   3.5   
54  0.580995    30721                1967  0.354331   0.645669   4.0   
5   0.614325    39421                 919  0.446732   0.553268   3.5   
1   0.622633    80363                 919  0.420200   0.579800   3.5   
32  0.629407    54278                 924  0.404915   0.595085   3.5   
38  0.626367     5620                 924  0.408673   0.591327   3.5   
36  0.626735    93326                 924  0.400245   0.599755   3.5   
8   0.606481   128592                 919  0.450424   0.549576   3.5   
49  0.589229    48909                1967  0.332704   0.667296   4.0   
35  0.627276    43906                 924  0.382411   0.617589   3.5   
4   0.618219     5891                 919  0.393320   0.606680   3.5   
15  0.598467   104736                 919  0.416430   0.583570   3.5   
14  0.599286    82366                 919  0.411886   0.588114   3.5   
7   0.607167     8861                 919  0.388770   0.611230   3.5   
17  0.596884   116191                 919  0.403386   0.596614   3.5   
12  0.602088    55232                 919  0.392624   0.607376   3.5   
11  0.603042     5413                 919  0.389653   0.610347   3.5   
16  0.597007    92938                 919  0.400116   0.599884   3.5   
6   0.607290     5717                 919  0.3738

In [13]:
# y = 1

def get_movie_cluster_rank(x):
#     print(x['movieId'])
    x['cluster_rank'] = 1
#     y += 1
    
    return x
    
ranking_df['cluster_rank'] = None
ranking_df = ranking_df.apply(lambda x: get_movie_cluster_rank(x), axis=1)
ranking_df

S_c  movieId  Candidate Movie Id       S_u  diversity  R_cu  \
40  0.628148     8140                1967  0.438028   0.561972   4.0   
42  0.609621   134246                1967  0.437159   0.562841   4.0   
41  0.620583    95604                1967  0.393092   0.606908   4.0   
43  0.607522   104736                1967  0.416430   0.583570   4.0   
47  0.594674     1156                1967  0.442604   0.557396   4.0   
52  0.582975     5806                1967  0.463797   0.536203   4.0   
48  0.589853   130474                1967  0.429003   0.570997   4.0   
57  0.579527    77810                1967  0.468731   0.531269   4.0   
20  0.664744   117368                 924  0.452133   0.547867   3.5   
50  0.587856     6073                1967  0.429540   0.570460   4.0   
56  0.580283    26791                1967  0.457312   0.542688   4.0   
44  0.600404   157338                1967  0.394845   0.605155   4.0   
46  0.595504    81641                1967  0.401434   0.598566   4.0   
55  0.580897      787                1967  0.433163   0.566837   4.0   
21  0.656645    54734                 924  0.456535   0.543465   3.5   
45  0.596366   161954                1967  0.395021   0.604979   4.0   
53  0.582721    33750                1967  0.401588   0.598412   4.0   
22  0.645606    39421                 924  0.446732   0.553268   3.5   
59  0.578970   170645                1967  0.402790   0.597210   4.0   
24  0.637025    50189                 924  0.451356   0.548644   3.5   
23  0.638894    44193                 924  0.427634   0.572366   3.5   
26  0.634328     7169                 924  0.432740   0.567260   3.5   
58  0.579470    51167                1967  0.377678   0.622322   4.0   
30  0.629755     8869                 924  0.437582   0.562418   3.5   
25  0.634817     8808                 924  0.421689   0.578311   3.5   
29  0.630887    47122                 924  0.428962   0.571038   3.5   
27  0.633632   110773                 924  0.420495   0.579505   3.5   
0   0.629817    96691                 919  0.429743   0.570257   3.5   
37  0.626615   134246                 924  0.437159   0.562841   3.5   
3   0.620348    50189                 919  0.451356   0.548644   3.5   
33  0.628614     8643                 924  0.423587   0.576413   3.5   
2   0.621326   134246                 919  0.437159   0.562841   3.5   
31  0.629642     6266                 924  0.411370   0.588630   3.5   
39  0.625870     5943                 924  0.419574   0.580426   3.5   
51  0.586604     4435                1967  0.349483   0.650517   4.0   
34  0.628115     7450                 924  0.413707   0.586293   3.5   
28  0.631951    77665                 924  0.405500   0.594500   3.5   
54  0.580995    30721                1967  0.354331   0.645669   4.0   
5   0.614325    39421                 919  0.446732   0.553268   3.5   
1   0.622633    80363                 919  0.420200   0.579800   3.5   
32  0.629407    54278                 924  0.404915   0.595085   3.5   
38  0.626367     5620                 924  0.408673   0.591327   3.5   
36  0.626735    93326                 924  0.400245   0.599755   3.5   
8   0.606481   128592                 919  0.450424   0.549576   3.5   
49  0.589229    48909                1967  0.332704   0.667296   4.0   
35  0.627276    43906                 924  0.382411   0.617589   3.5   
4   0.618219     5891                 919  0.393320   0.606680   3.5   
15  0.598467   104736                 919  0.416430   0.583570   3.5   
14  0.599286    82366                 919  0.411886   0.588114   3.5   
7   0.607167     8861                 919  0.388770   0.611230   3.5   
17  0.596884   116191                 919  0.403386   0.596614   3.5   
12  0.602088    55232                 919  0.392624   0.607376   3.5   
11  0.603042     5413                 919  0.389653   0.610347   3.5   
16  0.597007    92938                 919  0.400116   0.599884   3.5   
6   0.607290     5717                 919  0.3738

In [14]:
# ranks
ranking_df['composite_rank'] = ranking_df['composite_score'].rank(method='dense', ascending=False).astype(np.int)
ranking_df['d'] = abs(ranking_df['cluster_rank'] - ranking_df['composite_rank'])
ranking_df['d2'] = ranking_df['d'] ** 2

from scipy.stats import spearmanr
spearmanr(ranking_df['composite_rank'].values, ranking_df['cluster_rank'].values)
# spearman rank
# from scipy.stats import spearmanr 
# spearmanr(ranks.values)
# ranking_df.rank(method='dense')
# ranking_df

/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py:2530: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py:2531: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/usr/local/lib/python3.6/dist-packages/scipy/stats/_distn_infrastructure.py:877: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/usr/local/lib/python3.6/dist-packages/scipy/stats/_distn_infrastructure.py:877: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/usr/local/lib/python3.6/dist-packages/scipy/stats/_distn_infrastructure.py:1831: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)


SpearmanrResult(correlation=nan, pvalue=nan)

In [19]:
users_ratings['movieId'].values

array([    2,    29,    32,    47,    50,   112,   151,   223,   253,
         260,   293,   296,   318,   337,   367,   541,   589,   593,
         653,   919,   924,  1009,  1036,  1079,  1080,  1089,  1090,
        1097,  1136,  1193,  1196,  1198,  1200,  1201,  1208,  1214,
        1215,  1217,  1219,  1222,  1240,  1243,  1246,  1249,  1258,
        1259,  1261,  1262,  1266,  1278,  1291,  1304,  1321,  1333,
        1348,  1350,  1358,  1370,  1374,  1387,  1525,  1584,  1750,
        1848,  1920,  1967,  1994,  1997,  2021,  2100,  2118,  2138,
        2140,  2143,  2173,  2174,  2193,  2194,  2253,  2288,  2291,
        2542,  2628,  2644,  2648,  2664,  2683,  2692,  2716,  2761,
        2762,  2804,  2872,  2918,  2944,  2947,  2959,  2968,  3000,
        3030,  3037,  3081,  3153,  3265,  3438,  3476,  3479,  3489,
        3499,  3889,  3932,  3996,  3997,  4011,  4027,  4105,  4128,
        4133,  4226,  4306,  4446,  4467,  4571,  4720,  4754,  4878,
        4896,  4911,

# User-Item Similarity - Not considering for now
 - This is currently calculated only for selected users as total number of users is 138k, required memory for vectorized calculations is huge, or else non-vectorized approach would take a huge computation time.

In [21]:
from sklearn.metrics import pairwise_distances_chunked
from sklearn.metrics import pairwise_distances
from time import time

item_terms = genome_scores_df.values
user_terms = user_genome_vector_df.values
item_user_df = pd.DataFrame()

start = time()
chunked_D = pairwise_distances_chunked(item_terms, user_terms, metric='cosine')
finish = time() - start
# chunked_D
# for ch in chunked_D:
#     print(ch.shape)
#     ser = pd.Series(ch)
#     df = pd.DataFrame(ch)
#     item_user_df = item_user_df.append(df, ignore_index=True)

# item_user_df

# item_user_df
# next(chunked_D)

<generator object pairwise_distances_chunked at 0x7f27b42fe6d0>

In [13]:
item_user_df.columns = user_genome_vector_df.index
item_user_df

1         2         3         4         5         6         7       \
0    0.182797  0.195698  0.181683  0.170309  0.134807  0.161988  0.166592   
1    0.235734  0.235989  0.233729  0.198906  0.201326  0.188829  0.213849   
2    0.226365  0.195598  0.207718  0.151478  0.174460  0.144842  0.159628   
3    0.266561  0.247323  0.249059  0.222977  0.205804  0.176194  0.176155   
4    0.320277  0.285480  0.300185  0.237588  0.244874  0.212194  0.237100   
5    0.182905  0.203559  0.194447  0.194842  0.205052  0.244803  0.210912   
6    0.282332  0.262023  0.265110  0.233556  0.205125  0.167952  0.181314   
7    0.261736  0.264689  0.259825  0.220974  0.220445  0.217717  0.221427   
8    0.340095  0.314466  0.324969  0.244408  0.310847  0.265339  0.309427   
9    0.271556  0.232853  0.240200  0.178734  0.236537  0.203373  0.241535   
10   0.287220  0.268048  0.258848  0.223061  0.187822  0.170440  0.184236   
11   0.316832  0.314381  0.310608  0.282883  0.321263  0.280414  0.294316   
12   0.375255  0.374239  0.373423  0.336063  0.310240  0.325372  0.327123   
13   0.241939  0.245738  0.235740  0.266352  0.236659  0.270567  0.226782   
14   0.287700  0.272032  0.283118  0.232592  0.268614  0.228406  0.259028   
15   0.211448  0.240927  0.226473  0.254061  0.244964  0.294937  0.245698   
16   0.293629  0.310556  0.299400  0.319152  0.241305  0.265753  0.239442   
17   0.180882  0.200883  0.193310  0.210865  0.222503  0.225742  0.200863   
18   0.341288  0.324365  0.323976  0.271607  0.331338  0.298280  0.314862   
19   0.267220  0.245229  0.249906  0.176004  0.234392  0.196438  0.223624   
20   0.201205  0.228870  0.205934  0.218539  0.219833  0.236695  0.210555   
21   0.267119  0.256439  0.255580  0.226258  0.252503  0.245135  0.251550   
22   0.333048  0.310454  0.319747  0.230447  0.309049  0.270554  0.313423   
23   0.214430  0.186672  0.191847  0.210207  0.191039  0.179720  0.166849   
24   0.227264  0.250167  0.237976  0.306730  0.259228  0.303013  0.235296   
25   0.167265  0.179990  0.173069  0.202152  0.156636  0.177130  0.148306   
26   0.294749  0.278731  0.284177  0.266746  0.248232  0.236147  0.234449   
27   0.284146  0.306403  0.296099  0.319631  0.260505  0.280226  0.253761   
28   0.174743  0.203721  0.196726  0.288073  0.265407  0.293928  0.240543   
29   0.212815  0.230496  0.229155  0.283557  0.255296  0.288214  0.234747   
..        ...       ...       ...       ...       ...       ...       ...   
939  0.231806  0.242896  0.239256  0.290963  0.288939  0.302335  0.256912   
940  0.289546  0.290246  0.284149  0.282333  0.205337  0.246121  0.225244   
941  0.111398  0.113343  0.108427  0.088159  0.104964  0.134589  0.128471   
942  0.278533  0.230664  0.233404  0.261417  0.295518  0.257475  0.258603   
943  0.193050  0.190493  0.185519  0.205198  0.168471  0.185775  0.149916   
944  0.148002  0.140463  0.144114  0.158227  0.163503  0.166540  0.148816   
945  0.267483  0.273129  0.266702  0.273371  0.269470  0.260907  0.255197   
946  0.249500  0.259078  0.246256  0.295471  0.245239  0.273780  0.229321   
947  0.256162  0.241178  0.238519  0.221118  0.190196  0.185733  0.190270   
948  0.227674  0.210409  0.212870  0.209411  0.198923  0.174361  0.166135   
949  0.229792  0.225245  0.222315  0.254729  0.229307  0.237166  0.199591   
950  0.274986  0.264925  0.264719  0.276968  0.264264  0.254031  0.234864   
951  0.296716  0.302481  0.299917  0.337064  0.271743  0.291168  0.258482   
952  0.237257  0.226017  0.230838  0.161877  0.218264  0.190657  0.226297   
953  0.223505  0.215575  0.228434  0.210716  0.206562  0.221531  0.216341   
954  0.161594  0.174733  0.165410  0.197590  0.150899  0.174031  0.143946   
955  0.242476  0.254118  0.245120  0.297740  0.282020  0.304135  0.249836   
956  0.252080  0.245111  0.244917  0.274101  0.264958  0.264094  0.226921   
957  0.229919  0.229421  0.221484  0.238821  0.211209  0.225852  0.196088   
958  0.329537  0.293914  0.303610  0.235678  0.292091  0.241775  0.282210   
959

In [36]:
print(next(chunked_D))

[[0.01504303 0.01217182 0.00718734 ... 0.02824876 0.03232333 0.01035625]
 [0.02010743 0.02163612 0.01528878 ... 0.02700573 0.02132799 0.00858391]
 [0.06262721 0.04558198 0.0442124  ... 0.04694394 0.06603659 0.02475508]
 ...
 [0.04050054 0.04239141 0.02987979 ... 0.04371493 0.02317878 0.02072492]
 [0.05658456 0.07425358 0.05883723 ... 0.07833995 0.02384957 0.0474935 ]
 [0.03739842 0.0274528  0.02684695 ... 0.03198312 0.04780064 0.01381459]]


In [37]:
while(next())

[[0.06013426 0.04971034 0.04707826 ... 0.04396061 0.04715044 0.04200473]
 [0.03931588 0.03120174 0.02845041 ... 0.05293265 0.06395577 0.02424963]
 [0.02226199 0.01758179 0.02042588 ... 0.02679158 0.03740039 0.01575879]
 ...
 [0.01675692 0.02809588 0.01700051 ... 0.04224335 0.02143474 0.02028462]
 [0.0176327  0.01707151 0.01044839 ... 0.03320373 0.02849864 0.01543449]
 [0.02739982 0.0427438  0.02810045 ... 0.06975541 0.02536785 0.04319313]]
